const paths = [
  {
    id: "start",
    floor: "Primo piano",
    title: "Valle Incantata",
    description: "Una Valle silenziosa e piena di misteri. Gli alberi sembrano muoversi e sussurrare tra loro.",
    image: "/img/valle_incantata.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    exp: 0,
    drops: [
      {
        id: "",
        dropchance: 0,
      },
    ],
    options: [
      {
        id: "node_1",
        description: "Vai all'insediamento dei Goblin",
        image: "/img/goblin.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_2",
        description: "Vai alla Cripta",
        image: "/img/cripta.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_3",
        description: "Vai al Castello",
        image: "/img/castello.jpg",
        unlockRequirements: [],
      },
    ],
    posX: -146.0,
    posY: -91.0,
  },
  {
    id: "node_1",
    floor: "Primo piano",
    title: "Insediamento dei Goblin",
    description: "stai andando verso l'insediamento dei Goblin, ma lungo il percorso ti trovi davanti ad un ponte di legno con sotto un dirupo. Le assi scricchiolano al vento, alcune sembrano pronte a cedere. che cosa fai?",
    image: "/img/ponte.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    exp: 0,
    drops: [
      {
        id: "",
        dropchance: 0,
      },
    ],
    options: [
      {
        id: "node_4",
        description: "Attraversa il ponte",
        image: "/img/ponte_pericoloso.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_5",
        description: "Cerca un sentiero secondario",
        image: "/img/sentiero.jpg",
        unlockRequirements: [],
      },
    ],
    posX: -387.0,
    posY: 6.0,
  },
  {
    id: "node_2",
    floor: "Primo piano",
    title: "la Cripta sotterranea",
    description: "ti incammini verso la Cripta sotterranea. L'ingresso è seminascosto tra le radici di un grande albero contorto. Una scalinata di pietra umida scende nell'oscurità più profonda. Scendendo le scale senti il rumore di ossa che scricchiolano, sono gli scheletri che fanno di guardia alla cripta. Che cosa fai ?",
    image: "/img/interno_cripta.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    exp: 0,
    drops: [],
    options: [],
    posX: -176.0,
    posY: 67.0,
  },
  {
    id: "node_3",
    floor: "Primo piano",
    title: "Il Castello",
    description: "stai andando verso il Castello ma lungo il percorso incontri un mercante con una carrozza incastrata nel fango. Ti chiede aiuto per tirarla fuori, che cosa fai?",
    image: "/img/strada.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    exp: 0,
    drops: [],
    options: [],
    posX: 59.0,
    posY: 0.0,
  },
  {
    id: "node_4",
    floor: "Primo piano",
    title: "Il ponte cede",
    description: "Inizi a percorrere il ponte ma dopo qualche passo senti che inizia a cedere, preso dal panico inizi a correre per raggiungere la fine il prima possibile.\\nNella corsa cedono gli assi e finisci per cadere di sotto.",
    image: "/img/caduta.jpg",
    deathChance: 100,
    isBattle: false,
    enemyId: "",
    exp: 0,
    drops: [],
    options: [],
    posX: -559.0,
    posY: 131.0,
  },
  {
    id: "node_5",
    floor: "Primo piano",
    title: "Sentiero secondario",
    description: "Segui il sentiero secondario che serpeggia tra gli alberi. L’atmosfera è tranquilla, ma senti come se qualcuno ti stesse osservando…Ti giri e noti che un albero ti sta guardando.\n    L'albero ti parla con la sua voce cupa e profonda ma non riesci a capire cosa dice, che cosa fai?",
    image: "/img/sentiero.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    exp: 0,
    drops: [],
    options: [],
    posX: -327.0,
    posY: 214.0,
  },
];

export default paths;
