const paths = [
  {
    id: "start",
    floor: "Primo piano",
    title: "Valle Incantata",
    description:
      "Una Valle silenziosa e piena di misteri. Gli alberi sembrano muoversi e sussurrare tra loro.",
    image: "/img/valle_incantata.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "None",
    options: [
      {
        id: "node_1",
        description: "Goblin",
        image: "/img/goblin.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_2",
        description: "Cripta",
        image: "/img/cripta.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_3",
        description: "Castello",
        image: "/img/castello.jpg",
        unlockRequirements: [],
      },
    ],
    currencyReward: 0,
    posX: 280.0,
    posY: -342.0,
  },
  {
    id: "node_1",
    floor: "Primo piano",
    title: "Insediamento dei Goblin",
    description:
      "stai andando verso l'insediamento dei Goblin, ma lungo il percorso ti trovi davanti ad un ponte di legno con sotto un dirupo. Le assi scricchiolano al vento, alcune sembrano pronte a cedere. che cosa fai?",
    image: "/img/ponte.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [
      {
        id: "node_4",
        description: "Attraversa il ponte",
        image: "/img/ponte_pericoloso.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_5",
        description: "Cerca un sentiero secondario",
        image: "/img/sentiero.jpg",
        unlockRequirements: [],
      },
    ],
    posX: -8.0,
    posY: -261.0,
  },
  {
    id: "node_2",
    floor: "Primo piano",
    title: "la Cripta sotterranea",
    description:
      "ti incammini verso la Cripta sotterranea. L'ingresso è seminascosto tra le radici di un grande albero contorto. Una scalinata di pietra umida scende nell'oscurità più profonda. Scendendo le scale senti il rumore di ossa che scricchiolano, sono gli scheletri che fanno di guardia alla cripta. Che cosa fai ?",
    image: "/img/interno_cripta.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "None",
    options: [],
    currencyReward: 0,
    posX: 280.0,
    posY: -216.0,
  },
  {
    id: "node_3",
    floor: "Primo piano",
    title: "Il Castello",
    description:
      "stai andando verso il Castello ma lungo il percorso incontri un mercante con una carrozza incastrata nel fango. Ti chiede aiuto per tirarla fuori, che cosa fai?",
    image: "/img/carrozza.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [],
    posX: 535.0,
    posY: -305.0,
  },
  {
    id: "node_4",
    floor: "Primo piano",
    title: "Attraversa il ponte",
    description:
      "Inizi ad attraversare il ponte ma il primo asse di legno si spezza, afferri le due corse che lo sorreggono e prosegui lentamente, consapevole che potresti morire...",
    image: "/img/ponte_rotto.jpg",
    deathChance: 25,
    isBattle: false,
    enemyId: "None",
    options: [
      {
        id: "node_13",
        description: "Sopravvivi",
        image: "/img/continua.jpg",
        unlockRequirements: [],
      },
    ],
    posX: -186.0,
    posY: -134.0,
    currencyReward: 0,
  },
  {
    id: "node_5",
    floor: "Primo piano",
    title: "Sentiero secondario",
    description:
      "Segui il sentiero secondario che serpeggia tra gli alberi. L’atmosfera è tranquilla, ma senti come se qualcuno ti stesse osservando…Ti giri e noti che un albero ti sta guardando. L'albero ti parla con la sua voce cupa e profonda ma non riesci a capire cosa dice, che cosa fai?",
    image: "/img/albero_parlante2.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "None",
    options: [
      {
        id: "node_6",
        description: "Prosegui ",
        image: "/img/continua.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_7",
        description: "Parli con l'albero",
        image: "/img/albero_parlante.jpg",
        unlockRequirements: [],
      },
    ],
    currencyReward: 0,
    posX: 95.0,
    posY: -133.0,
  },
  {
    id: "node_6",
    floor: "Primo piano",
    title: "Arrivi all'insediamento",
    description:
      "Sei giunto all'insediamento, noti che ci sono 4 torri che lo circondano, ognuna con un arciere. Dentro ci sono guardie corazzate che fanno da guardia al baule, sicuramente custodiscono qualcosa di prezioso, che cosa fai?",
    image: "/img/insediamento_goblin.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [
      {
        id: "node_8",
        description: "Portone principale",
        image: "/img/portone_principale.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_9",
        description: "Entrata secondaria",
        image: "/img/entrata_secondaria.jpg",
        unlockRequirements: [],
      },
    ],
    posX: -64.0,
    posY: 33.0,
  },
  {
    id: "node_7",
    floor: "",
    title: "Nuovo Nodo",
    description: "",
    image: "",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [],
    posX: 188.0,
    posY: 28.0,
  },
  {
    id: "node_8",
    floor: "Primo piano",
    title: "Entri dal portone principale",
    description:
      "Cammini attaccato al muro per non farti vedere, apri leggermente il portone ed entri. Ti guardi intorno e noti che una guardia da lontano ha visto qualcosa muoversi e si sta avvicinando, che cosa fai?",
    image: "/img/guardia_goblin.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "None",
    options: [
      {
        id: "node_10",
        description: "Combatti",
        image: "/img/combattimento_guardia.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_11",
        description: "Ti nascondi",
        image: "/img/nascondersi.jpg",
        unlockRequirements: [],
      },
    ],
    currencyReward: 0,
    posX: -202.2741020793951,
    posY: 168.2192816635161,
  },
  {
    id: "node_9",
    floor: "Primo piano",
    title: "Cerchi un entrata secondaria",
    description:
      "Ti muovi furtivamente tra i cespugli per non farti vedere dagli arcieri, quando improvvisamente dentro un cespuglio si apre una botola e cadi di sotto. Ti ritrovi in una sorta di caverna buia e vedi da lontano una statua illuminata dalla luce naturale, che cosa fai?",
    image: "/img/caverna.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [
      {
        id: "node_12",
        description: "Vai verso la statua",
        image: "/img/statua_dea.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_15",
        description: "Cerchi un'uscita",
        image: "/img/uscita.jpg",
        unlockRequirements: [],
      },
    ],
    posX: 600.0,
    posY: 120.0,
  },
  {
    id: "node_10",
    floor: "Primo piano",
    title: "Provi a combattere la guardia",
    description:
      "La guardia ti vede, suona un corno ed è pronta ad attaccarti!",
    image: "/img/guardia_goblin.jpg",
    deathChance: 0,
    isBattle: true,
    enemyId: "",
    options: [],
    posX: 0.0,
    posY: 240.0,
  },
  {
    id: "node_11",
    floor: "",
    title: "Nuovo Nodo",
    description: "",
    image: "",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [],
    posX: 150.0,
    posY: 240.0,
  },
  {
    id: "node_12",
    floor: "Primo piano",
    title: "Vai verso la statua",
    description:
      "Ti avvicini alla statua e noti che è la statua della dea della luce, alla base c'è una scritta che dice: 'Prega e sarai ricompensato'. Che cosa fai?",
    image: "/img/inchino.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [
      {
        id: "node_14",
        description: "Prega la dea",
        image: "/img/mani.jpg",
        unlockRequirements: [],
      },
      {
        id: "node_15",
        description: "Cerchi un'uscita",
        image: "/img/uscita.jpg",
        unlockRequirements: [],
      },
    ],
    posX: 300.0,
    posY: 240.0,
  },
  {
    id: "node_14",
    floor: "Primo piano",
    title: "Prega la dea",
    description:
      "Ti inchini davanti alla statua e inizi a pregare, dopo qualche secondo gli occhi della dea si illuminano, la dea è grata per la tua preghiera e ti da la sua benedizione. Guadagni l'Abilità Fendente Divino! La tua arma ora è a + 10",
    image: "/img/spada_divina.jpg",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [
      {
        id: "node_15",
        description: "Ti allonatani e cerchi un'uscita",
        image: "/img/uscita.jpg",
        unlockRequirements: [],
      },
    ],
    posX: 450.0,
    posY: 240.0,
  },
  {
    id: "node_15",
    floor: "",
    title: "Nuovo Nodo",
    description: "",
    image: "",
    deathChance: 0,
    isBattle: false,
    enemyId: "",
    options: [],
    posX: 600.0,
    posY: 240.0,
  },
  {
    title: "New Node",
    description: "",
    image: "",
    isBattle: false,
    enemyId: "",
    currencyReward: 0,
    options: [],
    id: "node_13",
    deathChance: 0,
  },
];

export default paths;
